In [45]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [54]:
from preprocess import MusicHistory

base_dir = 'data/my_spotify_data/Spotify Account Data'
music = MusicHistory(base_dir)

Reading StreamingHistory_music_0.json..
Reading StreamingHistory_music_1.json..
Reading StreamingHistory_music_2.json..
Reading TasteProfile.json..
Reading YourLibrary.json..
Reading YourSoundCapsule.json..
dict_keys(['stats', 'highlights'])

In [26]:
stream_hist = music.streaming_history
stream_hist.sort_values(by='endTime', ascending=True)
# stream_hist.endTime.value_counts()

,endTime,artistName,trackName,msPlayed,endTime_dt
0,2025-07-11 23:53,The Beatles,Ticket To Ride - Remastered 2009,158036,2025-07-11 23:53:00
1,2025-07-12 00:01,The Beatles,Ticket To Ride - Remastered 2009,324,2025-07-12 00:01:00
2,2025-07-12 00:07,Justin Hurwitz,The Landing,331947,2025-07-12 00:07:00
3,2025-07-12 00:10,The Raconteurs,"Steady, As She Goes",168877,2025-07-12 00:10:00
4,2025-07-12 00:12,The Smiths,"Please, Please, Please, Let Me Get What I Want...",112706,2025-07-12 00:12:00
...,...,...,...,...,...
2197,2026-07-12 23:41,The Neighbourhood,Sweater Weather,240400,2026-07-12 23:41:00
2198,2026-07-12 23:44,Lord Huron,The Night We Met,208227,2026-07-12 23:44:00
2199,2026-07-12 23:48,Ricky Montgomery,Line Without a Hook,249587,2026-07-12 23:48:00
2200,2026-07-12 23:53,Ed Sheeran,Perfect,263400,2026-07-12 23:53:00
2201,2026-07-12 23:57,Tom Odell,Another Love,244360,2026-07-12 23:57:00

In [44]:
tasteprofiles = music.taste_profile['artistUris']
music.library[music.library.uri.isin(tasteprofiles)]

Empty DataFrame
Columns: [artist, album, track, uri]
Index: []

In [53]:
music.library.sort_values(by='msPlayed', ascending=False)

,artist,album,track,uri,endTime,msPlayed,endTime_dt
12830,Swans,To Be Kind,Bring The Sun/Toussaint L'Ouverture,spotify:track:6QXQEeKlpcEtg5eOJfr8nO,2026-01-15 21:38,1716436.0,2026-01-15 21:38:00
12180,System Of A Down,Mezmerize,Radio/Video,spotify:track:41pOIT2t1rvr2Trg1HQChZ,2025-10-29 21:04,1456174.0,2025-10-29 21:04:00
14756,The Microphones,Little Bird Flies into a Big Black Cloud,I Got Stabbed,spotify:track:0ANQU0FbcFqk3Fdk0v4pU1,2025-11-26 01:47,1449843.0,2025-11-26 01:47:00
8169,Mud Flow,Best Songs,The Sense of Me / Chemicals,spotify:track:0bhezzuZS8QPoVwZppyXgn,2026-01-31 23:56,1378897.0,2026-01-31 23:56:00
4230,Lorien Testard,Clair Obscur: Expedition 33 (Original Soundtrack),Une vie à t'aimer,spotify:track:4QEXM9na0mWIIt5Hwbsges,2025-07-20 22:49,1224527.0,2025-07-20 22:49:00
...,...,...,...,...,...,...,...
15135,Queens of the Stone Age,...Like Clockwork,The Vampyre of Time And Memory,spotify:track:5q453TyHMg7pxYdNG9nufn,NaN,NaN,NaT
15819,Grace Cathedral Park,In the Evenings of Regret,It's All Well Above Wonder Anyway,spotify:track:4AhSvS8COVUa2BplVN85Jh,NaN,NaN,NaT
15841,UNKLE,Psyence Fiction,Rabbit In Your Headlights,spotify:track:4z11Etf60lVE01ki1avHuD,NaN,NaN,NaT
16196,Sons of an Illustrious Father,Sons,Very Few Dancers,spotify:track:20Ywpk7eIYByt8g7qyv9Kz,NaN,NaN,NaT
16396,Sigur Rós,Ágætis Byrjun,Hjartað hamast,spotify:track:7a3KAxwAi2JXrrCvSfmkwT,NaN,NaN,NaT

In [48]:
music.library.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16413 entries, 0 to 16412
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   artist      16413 non-null  object
 1   album       16413 non-null  object
 2   track       16413 non-null  object
 3   uri         16413 non-null  object
 4   endTime     16291 non-null  object
 5   artistName  16291 non-null  object
 6   trackName   16291 non-null  object
 7   msPlayed    16291 non-null  float64
 8   endTime_dt  16291 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 1.1+ MB

In [56]:
music.highlights

[{'date': '2026-07-05',
  'highlightType': 'ON_REPEAT',
  'onRepeatHighlight': {'entity': 'The Color That Your Eyes Changed With the Color of Your Hair',
   'streamCount': 8}},
 {'date': '2026-06-28',
  'highlightType': 'MILESTONE',
  'multiEntityMilestoneHighlight': {'entities': ['The Antlers',
    'Radiohead',
    'Green Day',
    'The Unforgiven II',
    'Wake Me up When September Ends',
    'The Unforgiven - Remastered 2021',
    'Atrophy',
    'Thru The Eyes Of Ruby - Remastered 2012',
    'Pictures of Me'],
   'milestoneListeningSeconds': 148743}},
 {'date': '2026-06-21',
  'highlightType': 'STREAKS',
  'streaksHighlight': {'entity': 'Bright Eyes', 'dayStreaks': 5}},
 {'date': '2026-06-14',
  'highlightType': 'PROPORTION_LISTENING_ENTITY',
  'proportionListeningHighlight': {'entity': ':(',
   'listeningPercentage': 99.23052718899282}},
 {'date': '2026-06-07',
  'highlightType': 'ON_REPEAT',
  'onRepeatHighlight': {'entity': 'Gimme Shelter', 'streamCount': 6}},
 {'date': '2026-05-31',
  'highlightType': 'UNLIKE_COMBINATION',
  'unlikeCombinationHighlight': {'firstEntity': 'Moth To A Flame (with The Weeknd)',
   'secondEntity': 'The Hurricane'}},
 {'date': '2026-05-24',
  'highlightType': 'MILESTONE',
  'milestoneHighlight': {'entity': ':(', 'milestoneListeningSeconds': 103812}},
 {'date': '2026-05-17',
  'highlightType': 'YOU_STAND_OUT',
  'youStandOutHighlight': {'entity': 'Radiohead',
   'country': 'US',
   'secondsPlayed': 7674,
   'marketAvgSecondsPlayed': 858.5097}},
 {'date': '2026-05-10',
  'highlightType': 'PROPORTION_LISTENING_ENTITY',
  'proportionListeningHighlight': {'entity': 'Metallica',
   'listeningPercentage': 36.03213056228484}},
 {'date': '2026-05-03',
  'highlightType': 'STREAKS',
  'streaksHighlight': {'entity': 'Sufjan Stevens', 'dayStreaks': 7}},
 {'date': '2026-04-26',
  'highlightType': 'STREAKS',
  'streaksHighlight': {'entity': 'System Of A Down', 'dayStreaks': 5}},
 {'date': '2026-04-19',
  'highlightType': 'ON_REPEAT',
  'onRepeatHighlight': {'entity': 'Myth', 'streamCount': 8}},
 {'date': '2026-04-12',
  'highlightType': 'STREAKS',
  'streaksHighlight': {'entity': 'The Antlers', 'dayStreaks': 7}},
 {'date': '2026-04-05',
  'highlightType': 'MILESTONE',
  'multiEntityMilestoneHighlight': {'entities': ['The Antlers',
    'Radiohead',
    'Beach House',
    'Man of War',
    'Gimme Shelter',
    'No One Is Ever Going to Want Me',
    'Degausser',
    'Atrophy',
    'Armchairs'],
   'milestoneListeningSeconds': 105950}},
 {'date': '2026-03-29',
  'highlightType': 'PROPORTION_LISTENING_ENTITY',
  'proportionListeningHighlight': {'entity': 'The Rolling Stones',
   'listeningPercentage': 47.5095959825831}},
 {'date': '2026-03-22',
  'highlightType': 'ON_REPEAT',
  'onRepeatHighlight': {'entity': 'Pictures of Me', 'streamCount': 20}},
 {'date': '2026-03-15',
  'highlightType': 'STREAKS',
  'streaksHighlight': {'entity': 'Queens of the Stone Age', 'dayStreaks': 7}},
 {'date': '2026-03-08',
  'highlightType': 'YOU_STAND_OUT',
  'youStandOutHighlight': {'entity': 'Radiohead',
   'country': 'US',
   'secondsPlayed': 4878,
   'marketAvgSecondsPlayed': 902.6665}},
 {'date': '2026-03-01',
  'highlightType': 'MILESTONE',
  'milestoneHighlight': {'entity': 'Silver Mt. Zion',
   'milestoneListeningSeconds': 43163}},
 {'date': '2026-02-22',
  'highlightType': 'PROPORTION_LISTENING_ENTITY',
  'proportionListeningHighlight': {'entity': ':(',
   'listeningPercentage': 44.86451612903225}},
 {'date': '2026-02-15',
  'highlightType': 'ON_REPEAT',
  'onRepeatHighlight': {'entity': 'Plush', 'streamCount': 9}},
 {'date': '2026-02-08',
  'highlightType': 'MILESTONE',
  'multiEntityMilestoneHighlight': {'entities': ['The Antlers',
    'Queens of the Stone Age',
    'The Smiths',
    'Murder And Crime',
    'Chemicals',
    'Lazy Eyelids',
    'Myth',
    'Farewell to All These Rotten Teeth',
    'Armchairs'],
   'milestoneListeningSeconds': 136712}},
 {'date': '2026-02-01',
  'highlightType': 'STREAKS',
  'streaksHighlight': {'entity': 'Until The End', 'dayStreaks': 3}},
 {'date': '2026-01-25',
  'highlightType': 'YOU_STAND_OUT',
  'youStandOutHighlight': {'entity': 'Deftones',
   'country': 'US',
   'secondsPlayed': 4868,
   'marketAvgSecondsPlayed': 1263.9349}},
 {'date': '2026-01-18',
  'highlightType': 'ON_REPEAT',
  'onRepeatHighlight': {'entity': 'The Piano Song', 'streamCount': 10}},
 {'date': '2026-01-11',
  'highlightType': 'MILESTONE',
  'milestoneHighlight': {'entity': ':(', 'milestoneListeningSeconds': 38090}},
 {'date': '2026-01-04',
  'highlightType': 'PROPORTION_LISTENING_ENTITY',
  'proportionListeningHighlight': {'entity': ':(',
   'listeningPercentage': 62.3625311286755}},
 {'date': '2025-12-28',
  'highlightType': 'STREAKS',
  'streaksHighlight': {'entity': 'Is There Anybody Here?', 'dayStreaks': 3}}]